"""
SKILL.md 转换器
将现有的 Python 格式技能转换为 OpenSkills/Claude Skills 规范的 SKILL.md 格式
"""
import os
from pathlib import Path
from typing import Dict, Any

class SkillMDConverter:
    """技能MD转换器 - 将Python技能转换为SKILL.md格式"""
    
    def __init__(self):
        self.skill_conversion_rules = {
            'context_analysis': self._convert_context_analysis_to_md,
            'temp_workspace': self._convert_temp_workspace_to_md,
            'git_operations': self._convert_git_operations_to_md,
            'progressive_disclosure': self._convert_progressive_disclosure_to_md,
            'constitutional_validator': self._convert_constitutional_validator_to_md
        }
    
    def convert_python_skill_to_skill_md(self, skill_name: str, python_file_path: str, output_dir: str) -> str:
        """将Python技能转换为SKILL.md格式"""
        # 读取Python文件内容
        with open(python_file_path, 'r', encoding='utf-8') as f:
            python_content = f.read()
        
        # 生成SKILL.md内容
        if skill_name in self.skill_conversion_rules:
            skill_md_content = self.skill_conversion_rules[skill_name](python_content)
        else:
            # 通用转换规则
            skill_md_content = self._convert_generic_skill_to_md(skill_name, python_content)
        
        # 创建输出目录
        output_path = Path(output_dir) / skill_name
        output_path.mkdir(parents=True, exist_ok=True)
        
        # 写入SKILL.md文件
        skill_md_file = output_path / "SKILL.md"
        with open(skill_md_file, 'w', encoding='utf-8') as f:
            f.write(skill_md_content)
        
        return str(skill_md_file)
    
    def _convert_context_analysis_to_md(self, python_content: str) -> str:
        """转换上下文分析技能为SKILL.md格式"""
        return """---
name: context-analysis
description: Analyze and optimize context quality using constitutional principles
---

# Context Analysis Skill

Analyze the quality of provided context using five-dimensional metrics: clarity, relevance, completeness, consistency, and efficiency.

## Purpose

This skill evaluates the quality of input context and provides recommendations for improvement. It implements constitutional validation to ensure all analysis follows cognitive optimization principles.

## When to Use

Use this skill when:
- Evaluating the quality of requirements or specifications
- Assessing context clarity and completeness
- Identifying areas for context improvement
- Performing constitutional compliance checks

## Instructions

To analyze context quality:

1. Provide context to analyze in request parameters
2. Execute skill with context input
3. Review quality metrics and suggestions
4. Apply recommendations as needed

Format input as:
```
{
    "context": "Text to analyze",
    "detailed": true/false
}
```

## Output Format

Returns analysis results with:
- Five-dimensional quality metrics (0.0-1.0)
- Optimization suggestions
- Identified issues
- Detailed recommendations when requested

## Constitutional Compliance

This skill ensures all output complies with constitutional principles:
- Progressive disclosure: Information organized by importance
- Cognitive convenience: Minimal cognitive load for AI processing
- Information encapsulation: Self-contained results
- Cognitive gestalt: Complete cognitive units

## Best Practices

- Use detailed mode for comprehensive analysis
- Apply suggestions iteratively for context improvement
- Combine with other analysis skills for full assessment
- Validate against constitutional principles
"""
    
    def _convert_temp_workspace_to_md(self, python_content: str) -> str:
        """转换临时工作区技能为SKILL.md格式"""
        return """---
name: temp-workspace
description: Manage AI-generated temporary files to prevent project pollution through constitutional compliance
---

# Temporary Workspace Skill

Manage temporary files generated by AI assistants to prevent Git repository pollution while ensuring constitutional compliance.

## Purpose

This skill provides a secure temporary workspace for AI-generated content that can be reviewed and confirmed before integration into the main project. All operations follow constitutional principles.

## When to Use

Use this skill when:
- Working with AI-generated content that may need review
- Creating temporary files that shouldn't be committed
- Managing AI-assisted development workflows
- Ensuring constitutional compliance of file operations

## Instructions

To create workspace:
1. Execute "create-workspace" operation
2. Add files using "add-file" operation
3. Review and confirm necessary files
4. Clean workspace when complete

Available operations:
- "create-workspace": Initialize temporary workspace
- "add-file": Add file to workspace
- "confirm-file": Move file to confirmed area
- "confirm-all": Confirm all files
- "list-files": View workspace status
- "clean-workspace": Remove temporary files

## Constitutional Compliance

All file operations are subject to constitutional checks:
- Prevents temporary files from polluting Git
- Validates content before confirmation
- Maintains workspace isolation
- Preserves project integrity

## Security Features

- Automatic detection of potentially unsafe content
- Prevention of temporary files in Git commits
- Isolated workspace management
- Constitutional validation of all operations
"""
    
    def _convert_git_operations_to_md(self, python_content: str) -> str:
        """转换Git操作技能为SKILL.md格式"""
        return """---
name: git-operations
description: Perform Git operations with constitutional validation and temporary file protection
---

# Git Operations Skill

Perform Git operations with constitutional validation and automatic protection against temporary file pollution.

## Purpose

This skill executes Git operations while ensuring constitutional compliance and preventing temporary files from being committed. It implements project constitution rules for safe version control.

## When to Use

Use this skill when:
- Performing Git operations with safety checks
- Ensuring constitutional compliance in commits
- Preventing accidental temporary file commits
- Applying project constitution rules to Git

## Instructions

To perform Git operations:

1. Configure Git repository with constitutional rules
2. Execute desired Git operation
3. Review operation results
4. Verify constitutional compliance

Supported operations:
- "setup-constitution": Initialize project constitution
- "smart-commit": Commit with constitutional validation
- "add-commit": Add and commit with validation
- "status-check": Check Git and constitutional status
- "install-hooks": Install constitutional Git hooks

## Constitutional Compliance

This skill enforces:
- Temp file detection in staging area
- Constitutional validation of commit messages
- Project constitution adherence
- Secure operation execution

## Project Constitution

The skill implements project constitution with rules:
- All AI-generated content must be validated before commit
- Temporary files are automatically ignored
- Commit messages follow constitutional format
- Security and quality checks are mandatory
"""
    
    def _convert_progressive_disclosure_to_md(self, python_content: str) -> str:
        """转换渐进披露技能为SKILL.md格式"""
        return """---
name: progressive-disclosure
description: Create directory structures following constitutional principles with progressive disclosure
---

# Progressive Disclosure Skill

Create directory structures and organize content following constitutional principles with progressive disclosure implementation.

## Purpose

This skill creates project structures that support progressive disclosure, allowing information to be accessed at different levels of detail. All structures follow constitutional design principles.

## When to Use

Use this skill when:
- Creating new project directory structures
- Organizing content with progressive disclosure
- Implementing hierarchical information organization
- Following constitutional design principles

## Instructions

To create progressive disclosure structures:

1. Define project requirements
2. Execute skill to create structure
3. Organize content hierarchically
4. Apply progressive disclosure principles

Parameters include:
- type: "basic", "intermediate", "advanced"
- project_name: Name of the project
- requirements: Project requirements for structure design

## Constitutional Compliance

Structures created follow constitutional principles:
- Progressive disclosure: Information accessible at different levels
- Cognitive convenience: Minimal cognitive load
- Information encapsulation: Self-contained modules
- Cognitive gestalt: Complete organizational units

## Structure Types

- Basic: Essential directories and files
- Intermediate: Modular components with documentation
- Advanced: Complete architecture with full documentation
"""
    
    def _convert_constitutional_validator_to_md(self, python_content: str) -> str:
        """转换宪法验证器为SKILL.md格式"""
        return """---
name: constitutional-validator
description: Validate content against constitutional principles using AI-native intelligence
---

# Constitutional Validator Skill

Validate content against constitutional principles using AI-native intelligence with progressive disclosure implementation.

## Purpose

This skill validates any content against four core constitutional principles: progressive disclosure, cognitive convenience, information encapsulation, and cognitive gestalt. It ensures all generated content follows cognitive optimization principles.

## When to Use

Use this skill when:
- Validating content for constitutional compliance
- Checking generated content quality
- Ensuring cognitive optimization principles
- Applying constitutional constraints

## Instructions

To validate constitutional compliance:

1. Provide content to validate
2. Specify principle to check (optional)
3. Execute validation
4. Review compliance results
5. Apply corrective actions if needed

Principles checked:
- "progressive_disclosure": Information hierarchy and access levels
- "cognitive_convenience": Clarity and cognitive load optimization  
- "information_encapsulation": Self-containment and boundary clarity
- "cognitive_gestalt": Cognitive unit completeness
- "all": All principles simultaneously

## Constitutional Principles

### Progressive Disclosure
- Information organized hierarchically
- Different detail levels available
- Minimal information overload

### Cognitive Convenience
- Clear, self-explanatory content
- Minimal cognitive load
- Accurate and unambiguous

### Information Encapsulation
- Self-contained units
- Clear boundaries and dependencies
- Autonomous modules

### Cognitive Gestalt
- Complete cognitive units
- Structural coherence
- Meaningful wholeness

## Validation Process

The skill performs constitutional validation by:
- Analyzing content structure and organization
- Checking cognitive optimization metrics
- Verifying principle compliance
- Generating improvement recommendations
"""
    
    def _convert_generic_skill_to_md(self, skill_name: str, python_content: str) -> str:
        """通用技能转换规则"""
        return f"""---
name: {skill_name}
description: Convert {skill_name} skill to follow constitutional and progressive disclosure principles
---

# {skill_name.replace('-', ' ').title()} Skill

Convert the {skill_name} skill to follow constitutional and progressive disclosure principles.

## Purpose

This skill implements the {skill_name} functionality with constitutional compliance and progressive disclosure optimization. It ensures all operations follow cognitive convenience principles.

## When to Use

Use this skill when:
- Performing {skill_name.replace('-', ' ')} operations
- Ensuring constitutional compliance
- Applying progressive disclosure principles
- Following cognitive optimization patterns

## Instructions

To use the {skill_name} skill:

1. Prepare input parameters
2. Execute skill with constitutional validation
3. Review output for compliance
4. Apply progressive disclosure as needed

## Constitutional Compliance

This skill enforces constitutional principles:
- Progressive disclosure: Graduated access to information
- Cognitive convenience: Minimal processing load
- Information encapsulation: Self-contained operations
- Cognitive gestalt: Complete cognitive units

## Output Format

Returns results in constitutional-compliant format with progressive disclosure structure.
"""

# 全局转换器实例
SKILL_MD_CONVERTER = SkillMDConverter()